export const API_V1 = "/api/v1.0";

export const subjects = {
  WISDOM: 11,
  RIGHT_VIEW: 4,
  RIGHT_INTENTION:1,
  ETHICS: 10,
  RIGHT_SPEECH: 8,
  RIGHT_LIVELIHOOD: 3,
  RIGHT_ACTION: 6,
  MEDITATION: 9,
  RIGHT_EFFORT: 7,
  RIGHT_MINDFULNESS: 5,
  RIGHT_CONCENTRATION: 2
}